import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            display: "flex",
            gap: "20px",
            justifyContent: "center",
            padding: "20px",
            backgroundColor: "#4675c0",
            fontSize: "20px",
            fontWeight: "bold",
            marginBottom: "20px",
          }}
        >
          <Link className="hover-scale" href="/">
            Home
          </Link>
          <Link className="hover-scale" href="/Pages/posts/">
            Posts
          </Link>
          <Link className="hover-scale" href="/Pages/articles/">
            Articles
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
